### PR TITLE
Release notes for v1.3.2.1

### PR DESCRIPTION
**Pull request by emrahkocaman**
Hello Dear Pivots,

Could you please have a look at this PR updating release notes for Hazelcast for PCF v1.3.2.1?

### CODE REVIEW

**Comment by ghanna2017** [comment]
Thanks @emrahkocaman!

**Comment by emrahkocaman** [comment]
👍 Thanks for the prompt response @ghanna2017

**Comment by jncd** [comment]
Hi @emrahkocaman Just to follow up... I tweaked the release notes a tad with some text that the Partners team here approved for me. It standardizes the language for all the tiles where this fix has been made.
Thanks for making the change to your tile. 
(You have the same change for the Jet beta tile coming soon?)
jane

**Comment by emrahkocaman** [comment]
Hi @jncd , thanks for the update, it's much better than mine :)
Same change is on the way for Jet tile but it has its own release cycle, should be out next week.

**Pull request merged**
